# If having issues check the image tag on docker hub
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  # after testing shut down container then remove this
  helloworld:
    image: 'karthequian/helloworld:latest'
    container_name: helloworld
    restart: unless-stopped
    ports:
      - 8888:80/tcp

volumes:
  data:
  letsencrypt:

