#If having issues check docker hub for image tag 
services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:20250822_112758
    init: true
    restart: always
    # This line is not allowed to be changed.
    container_name: nextcloud-aio-mastercontainer 
    network_mode: bridge
    volumes:
      # This line is not allowed to be changed.
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8088:8080
    environment:
      # Community containers https://github.com/nextcloud/all-in-one/tree/main/community-containers
      AIO_COMMUNITY_CONTAINERS: "local-ai memories" 
      # Use this port in Nginx Proxy Manager
      APACHE_PORT: 11000 
      # NC_TRUSTED_PROXIES: 172.18.0.3  # this is the NPM proxy ip address in the docker network !
      FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M"
      # ⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done!
      NEXTCLOUD_DATADIR: /nextclouddocker/ncdata 
      # NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host.
      NEXTCLOUD_UPLOAD_LIMIT: 1028G
      NEXTCLOUD_MAX_TIME: 7200
      NEXTCLOUD_MEMORY_LIMIT: 1028M
      # Intel QuickSync go to false if not using
      NEXTCLOUD_ENABLE_DRI_DEVICE: true 
      # This should only be set to true if things are correctly configured.
      SKIP_DOMAIN_VALIDATION: true 
      # This allows to adjust the port that the talk container is using which is exposed on the host. See https://github.com/nextcloud/all
      TALK_PORT: 3478 
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed.
